language: java
jdk: oraclejdk8
sudo: reqired # faster builds

before_script:
  - sudo chmod 755 /home/travis/build/WMerk/vnv/src/test/resources/chromedriver.exe
  - sudo chmod 755 /home/travis/build/WMerk/vnv/src/test/resources/chromedriver

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: "mvn test"

