language: java
jdk: oraclejdk8
sudo: reqired # faster builds
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
 - sudo chmod 755 /home/travis/build/WMerk/vnv/src/test/resources/chromedriver.exe
  - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - npm i -g npm@^3
   - sleep 3

script: "mvn test"

